"""empty message

Revision ID: 14bb6a2b879e
Revises: 
Create Date: 2022-04-17 21:14:21.806106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bb6a2b879e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proizvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=60), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('img', sa.String(length=300), nullable=False),
    sa.Column('product_id', sa.String(length=60), nullable=False),
    sa.Column('price_id', sa.String(length=60), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('adresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('adresa', sa.String(length=50), nullable=False),
    sa.Column('broj_ulice', sa.String(length=10), nullable=False),
    sa.Column('broj_stana', sa.Integer(), nullable=True),
    sa.Column('grad', sa.String(length=50), nullable=False),
    sa.Column('postanski_broj', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adresa')
    op.drop_table('user')
    op.drop_table('proizvod')
    # ### end Alembic commands ###
