"""empty message

Revision ID: 29a9f7c14a2d
Revises: 9ad24716ade5
Create Date: 2022-04-27 16:52:42.017635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29a9f7c14a2d'
down_revision = '9ad24716ade5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narudzba')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narudzba',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proizvod_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('datum', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('kolicina', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], name='narudzba_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='narudzba_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'proizvod_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
