"""empty message

Revision ID: 9ad24716ade5
Revises: 
Create Date: 2022-04-27 16:31:17.585453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad24716ade5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proizvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=60), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('cena_proizvoda', sa.Integer(), nullable=False),
    sa.Column('valuta', sa.String(length=3), nullable=False),
    sa.Column('duzi_opis', sa.Text(), nullable=True),
    sa.Column('dostupna_kolicina', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=300), nullable=False),
    sa.Column('obrisan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naziv')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('adresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=True),
    sa.Column('prezime', sa.String(length=30), nullable=True),
    sa.Column('broj_telefona', sa.String(length=10), nullable=True),
    sa.Column('adresa', sa.String(length=50), nullable=True),
    sa.Column('broj_ulice', sa.String(length=10), nullable=True),
    sa.Column('grad', sa.String(length=50), nullable=True),
    sa.Column('drzava', sa.String(length=20), nullable=True),
    sa.Column('postanski_broj', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('narudzba',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proizvod_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('datum', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('kolicina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'proizvod_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narudzba')
    op.drop_table('adresa')
    op.drop_table('user')
    op.drop_table('proizvod')
    # ### end Alembic commands ###
