"""empty message

Revision ID: b6a53802a673
Revises: 29a9f7c14a2d
Create Date: 2022-04-27 17:16:43.395555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a53802a673'
down_revision = '29a9f7c14a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'customer_id')
    # ### end Alembic commands ###
